/* Write a java application to create an application software for a publisher      offering discount on purchase of books as per the chart given below:-
     Publisher   ------------    Discount in percentage on M.R.P.
        BPB        ------------                         30%
                                         Fundamental(1) --- Web Desiging(2) --- Language(3)
        TMH        ------------           15%                           20%                       30%
Calculate and print the Bill/Invoice  in the following format as 1% VAT is to be paid by the consumer on getting bill:-
                 = = = Bill/Invoice Details = = = Current Date&Time = = =
                 Publisher Name		:.......
optional-  Book type as 1/2/3		:.......
                 M.R.P. in Rs.		:.......
                Discount rate in Percentage	:.......
                Discount Amount in Rs.	:.......
                ----------------------------------------------------------------------------------
                Payable Amount in Rs.	:.......
                1% VAT Amount in Rs.	:.......
                ----------------------------------------------------------------------------------
                Net Bill/Invoice Amount in Rs.	:.......                              */
